from PyQt5 import  uic,QtWidgets
from PyQt5.QtWidgets import * 
from PyQt5.QtCore import Qt, QSortFilterProxyModel
from PyQt5.QtGui import QStandardItem, QStandardItemModel
#Cadastro do numeração das regiões:
zonas = ('SJ01','SJ01','SJ01','SJ01','SJ01','SJ01','SJ01','SJ01','SJ01','SJ01','SJ01','SJ01','SJ01','SJ01','SJ02','SJ02','SJ02','SJ02','SJ02','SJ02','SJ02','SJ02','SJ02','SJ02','SJ03','SJ03','SJ03','SJ03','SJ03','SJ03','SJ03','SJ03','SJ03','SJ03','SJ03','SJ03','SJ03','SJ03','SJ03','SJ03','SJ03','SJ03','SJ03','SJ03','SJ04','SJ04','SJ04','SJ04','SJ04',
'SJ04','SJ04','SJ04','SJ05','SJ05','SJ05','SJ05','SJ05','SJ05','SJ05','SJ05','SJ05','SJ05','SJ05','SJ06','SJ06','SJ06','SJ06','JC01','JC01','JC01','JC01','JC01','JC01','JC01',
'JC01','JC01','JC01','JC01','JC01','JC01','JC01','JC01','JC01','JC01','JC01','JC01','JC01','JC01','JC01','JC01','JC02','JC02','JC02','JC02','JC02','JC02','JC02','JC02','JC02',
'JC02','JC02','JC02','JC03','JC03','JC03','JC03','JC03','JC03','JC03','JC03','JC03','JC03','JC03','JC03','JC03','JC03','JC03','JC03','JC03','JC03','JC03','JC03','JC03','JC03',
'JC03','JC03','JC03','JC03','JC03','JC03','JC03','JC03','JC03','JC03','JC03','JC03','JC04','JC04','JC04','JC04','JC04','JC04','JC05','JC05','JC05','JC05','JC05','JC05','JC05',
'JC05','JC05','JC05','JC05','JC05','JC05','JC05','JC05','JC05','JC05','JC05','JC05','JC05','JC06','JC06','JC06','JC06','JC06','JC06','JC06','JC06','JC06','JC06','JC06','JC06',
'JC06','JC06','JC06','JC06','JC06','JC06','JC06','JC06','JC06','JC06','JC06','JC06','JC06','JC06','JC06','JC06','JC06','AB01','AB01','AB01','AB01','AB01','AB01','AB01','AB01',
'AB01','AB01','AB01','AB01','AB01','AB01','AB01','AB01','AB01','AB01','AB01','AB01','AB01','CM01','CM01','CM01','CM01','CM01','CM01','CM01','CM01','CM01','CM01','CM01','CM01',
'CM01','CM01','CM01','CM01','CM01','CM01','CM01','CM01','CM01','CM01','CM01','CM01','CM01','CM01','CM02','CM02','CM02','CM02','CM02','CM02','CM02','CM02','CM02','CM02','CM02',
'CM02','CM02','CM02','CM02','CM02','CM02','CM02','CM02','CM02','CM02','CM02','CM02','CM02','CM02','CM02','CM02','CM02','CM02','CM02','CM02','CM02','CM02','CM02','CM02','CM02',
'CM03','CM03','CM03','CM03','CM03','CM03','CM03','CM03','CM03','CM03','CM03','CM03','CM03','CM03','CM03','CM03','CM03','CM03','CM03','CM03','CM03','CM03','CM03','CM03','CM03',
'CM03','CM03','CM03','CM03','CM03','CM03','CM03','CM03','CM03','CM03','CM03','CM03','CM03','CM03','CM03','CM03','CM03','CM03','CM03','CM03','CM03','CM03','CM03','PU01','PU01','PU01','PU01','PU01','PU01','PU01','PU01','PU01','PU01','PU01','PU01','PU01','PU01','PU01','PU01','PU01','PU01','PU01','PU01','PU01','PU01','PU01','PU01','PU01','PU01','PU01','PU01','PU01','PU01','PU01','PU01','PU01','MC01','MC01','MC01','MC01','MC01','MC01','MC01','MC01','EX01','EX01','EX01','EX01','EX01','EX01','EX01','EX01','EX01','EX01','EX01','EX01','EX01','EX01','TR01','TR01','TR01','TR01','TR01','TR01','TR01','TR01','TR01','TR01','TR01','TR02','TR02','TR02','TR02','TR02','TR02','TR02','TR02','TR02','TR02','TR02','TR02','TR02','TR02','TR02','NT01','NT01','NT01','NT01','NT01','NT01','NT01','NT01','NT01',)
#Cadatro das regiões:
nome_região = ('ZUADOR','MACAIBA','PARNAMIRIM','CENTRO SJM','TANCREDO NEVES','PAU BRASIL','QUEBRA FUZIL','BAIRRO NOVO','VILA MARIA','KM 38','GOGO DA EMA','BRISA','CIDADE DE DEUS'
,'MAZAPA','MONTE ALEGRE','MENDES','VALE DO LIRIO', 'JAPECANGA','LARANJEIRAS COSME','JARDIM','MENDENZINHO','ARENAN','VERA CRUZ','COBE','LARANJEIRA ABDIAS','RIBEIRO','MANIMBU',
'CAJEIRA','SITIO SANTA LUZIA','SITIO BURACO','CURRAL NOVO','BOA VISTA','MUNDO NOVO CIMA','MUNDO NOVO BAIXO','URUCARA','RIO DO MEIO','NASCENCA','BREJINHO','SANTA ANTONIO',
'VARZEA','NOVA CRUZ','PATANE','GEOGINO AVELINO','ARES','GOLANDI','CURRAIS','GENIPAPEIRO','CARNAUBA','GEORGE AVELINO','PATANE','ARES','GOIANINHA','NISIA FLORESTA','TOROROMBA',
'MORRINHOS','OITIZEIRO','CAMPO SANTANA','CAMURUPOM','BARRETA','TABATINGA','TIMBO','PORTO','BUZIOS','MONTE ALEGRE','BREJINHO','SANTO ANTONIO','NOVA CRUZ','ASSUNÇÃO','RIACHO SECO',
'ZABELE','CAJA','BOA SORTE','BAIXA DO MACACO','LAGEADO','MORADA NOVA','PEDRA DAGUA','CENTRO','ASSENT SÃO LUIZ','MATÃO','ASSENT XOA','BREJINHO 1','BREJINHO 2','CORTE','JUA','AS 100',
'SERRA VERDE',' CHICO MENDES','ARRIBÃO','SANTO ANTONIO','ARACATI','SAMAMBAIA','CRAVO','BAIXO SÃO MIGUEL','SURUBIM','NOVA ALIANÇA','CONTADOR','POUSA','LAGOA SERROTE','LAGOA ZÉ GOMES',
'JERUZALEM','PARAGUAI','POÇO BRANCO','MARAJO','MODELO 1','MODELO 2','POV SÃO GERALDO','QUEIMADAS','OITICICA','BAIXA NOVILHO','POV SÃO FRANCISCO','POV AMAZONAS','PEREIROS','SANTA VITORIA',
'SÃO LUIZ','MARIA DA PAZ','PRIMEIRO DE JUNHO','LIMÃO','TRÊS IRMÃOS','BOA ESPERANÇA','BAIXINHA DOS FRANCA','QUIXABEIRA','BOM SUCESSO','BARREIROS','ACAUA','CANTO ILHA 1','CANTO ILHA 2',
'EXUQUEIMADO','PRAIA MARCOS','MORRO DOS PAULO','MORRO DOS MARTINS','PARAIZINHO','PEDRA GRANDE','SÃO BENTO DO NORTE','CAIÇARA DO NORTE','POV SÃO MIGUEL','FREJO','VALENTIM','FAZENDA NOVA',
'JARDIM DE ANGICOS','PRIMAVERA','ARRAIAL DOS BALBINOS','PEDRA PRETA','RIACHUELO','CACHOEIRA DO SAPO','SÃO PAULO DO POTENGI','CAIÇARA DO RIO DO VENTO','LADEIRA GRANDE','BEIRA DO RIO',
'POUSA 2','ARISCO','PASSAGEM DE PEDRA','PÉ QUEBRADO','QUINTURURE','SERRA DA CRUZ','ALTO DO RONDON','FECHADO 1','FECHADO 2','SANTA MARIA','ASSENT. CANADA','BENTO FERNANDES','ASSENT. PINHEIROS',
'ASSENT. TTL','AMARELÃO','SANTA TEREZINHA','SERRINHA DE BAIXO','SERRINHA DE CIMA','GOIS','ARUEIRA','VIVARA','NOVA DESCOBERTA','BAIXA DE ANGICOS','BOM TRABALHO','NOVA OLINDA','SÃO GERALDO',
'ALTO ORIENTE','PIRANGI','TERRA SANTA',' ASSENT. BOM JESUS','ASSENT. SÃO PEDRO','POV SÃO JÓSE','PEDRINHAS','NOVA CONQUISTA','ASSENT. BOA VISTA','CENTRO JANDAIRA','TUBIBAL','BARROCÃO',
'SERROTE DE BENTO','TRINCHEIRAS','GALINHOS','SANTA INES','GUARARAPES','PORTO DO MANGUE','PRAIA DO ROSADO','PRAIA PEDRA GRANDE','PONTA DO MEL','GROSSOS','PRAIA SÃO CRISTOVÃO',
'MORRO PINTADO','PRAIA DE REDONDO','SÃO JÓSE','CASQUEIRA','ARRAIAL','PEDRINHAS','CANTO DO AMARO','SERRA VERMELHA','FREIRE','GARAVELO 1','BOM JESUS','CASQUEIRA 2','CARAVELO 4',
'SERRA DO MEL(VILAS)','COHAB','CENTRO','PLANALTO','BROGODO','BARRETÃO','TERRA DA SANTA','SÃO GERALDO','NOVOS TEMPOS','COHAB','PARAIBA','SANTA AGUEDA','CAMURUPIM','VERDE NASCI',
'NOVA DESCOBERTA','VALE VERDE','BELA VISTA','JOÃO DE BARRO','SÃO JOSÉ','LOT PAPA FRANSCISCO','NOVO HORIZONTE','ESPIRITO SANTO','CINCO BOCAS','PASSA E FICA','NOVA CONQUISTA',
'MORAR MELHOR','VALE DO AMANHECER','SANTA PAULA','IMBURANA','RIO DOS INDIOS','COQUEIROS','ALTO DO SITIO','MURIU','GRAVATA','MANGABEIRA','LAGOA DO COSMO','PRIMAVERA','ANINGAS',
'MAXARANGUAPE','JACUMÃ','CARAUBAS','MARACAJAU','PITITINGA','PROJ SÃO MIGUEL','ASSENT SÃO JÃO','RIACHÃO DE FORA','RESISTENCIA POTIGUAR','BOA VISTA','CAPOEIRA GRANDE','CAIANA',
'CAPIM','ASSENT SÃO JÓSE','NOVO HORIZONTE','NOVA DIMENSÃO','CURICACA','RIACHO DAGUA','ASSENT ROSARIO','CANUDOS','TAMANDUA','MATURAIA','RIACHO DE GOIABEIRA',' RIACHÃO DE DENTRO',
'AGUAS VIVAS','NOVO HORIZONTE 2','IELMO MARINHO','FAZENDA NOVA','NOVA DESCOBERTA','SERROTE COBERTO','JURUMENHA','POROROCA','TAMOATA','QUERMISOL','SITIO PARAGUAIO','SÃO SEBASTIÃO 1',
'SÃO SEBASTIÃO 2','SÃO SEBATIÃO 3','ASSENT BARBARA','LOGRADOURO','ASSENT NOVA JERUSALEM','UMARIZEIRA','ARISCO DO BARBOSA','BOA VISTA TAIPU','JACOCA','PONTA DO MATO','NOVA ESPERANÇA',
'ALEGRIA','PACAVIRA','MAQUALHADA 1','MAQUALHADA 2','MAQUALHADA 3','SERRINHA','CANTO DE MOÇA','UMARI','CIDADE DE SANTA MARIA','PRIMEIRA LAGOA','SERRA PELADA','QUEIMADA TAIPU','GAMILEIRA TAIPU',
'MATÃO TAIPU','SÃO SEBASTIÃO 4','CIDADE TAIPU','ASSENT PADRE CICERO','GAMILEIRA IPANEMA','LAGOA NOVA 2','ARISCO DA GAMILEIRA','RAMANDA 1','RAMANDA 2','RAMANDA 3','RAMANDA 4','SITIO XINXAR',
'TIMBAUBA','ASSENT. MARIGUELA','CIDADE DE PUREZA','CAPELA','MATAS','MINEIROS','PROJETO SANTA AGUEDA','MANIBU','SANTA ANA','DUAS PASSAGENS','CACHOEIRA','RIACHO DO COITE','RIACHÃO DE DENTRO','ASSENT NOVA VIDA','MORADA NOVA','LAGOA DO GENIPAPO','DIAMENTE','SANTA RITA','PEDREGULHO','OLHO DAGUA','INGAR','ASSENT BERNA MARINS','BARRO VERMELHO','SITIO SILVERIA','BAIXA DO MEIO','ITABAIANA','MEU RANCHO','NOVA DESCOBERTA',' SÃO LOURENCO','VARZIA DE DENTRO','MINAMORA','PUREZA CENTRO','BEBIDA VELHA','BOA CICA','CANA BRAVA','BAIXA DO MEIO','MACAU','DIOGO LOPES','ILHAS','BARREIRAS','GUAMARE','MACAUZINHO','COHAB','EXTREMOZ CENTRO','RAPOSA','NOVA ESPERANÇA','MASSAGANA','TABUÃO','LAGOA GRANDE','LAGOA DA PORTA','ESTIVAS','ARACA','OITIZEIRO','PITANGUI','PEDRINHAS','VILA DE FATIMA','CARAO','CATOLÉ','PUNAU','SANTA LUZIA','CIDADE DE TOUROS','CARNAUBINHA','PEROBAS','RIO DO FOGO','ASSENT. ZUMBI','CANTO GRANDE','ZUMBI','DOM MARCOLINO','TABUA','REDUTO','ANGICOS DE FORA','ANTONIO CONSELHEIROS','PARAISO','ARIZONA','MUNDO NOVO','NOVO HORIZONTE','COLORADO','REDENÇÃO','PLANALTO','CANUDOS','BAIXA DO QUINQUIM','SA','SÃO MIGUEL DO GOSTOSO','MASSARANDUBA','GUAGIRU','CIDADE DAS RODAS','CIDADE DAS FLORES','JARDIM PETROPOLES','SÃO GONÇALO AMARANTE','IGAPO','CENTRO DE NATAL','PAJUSSARA')








modelo = QStandardItemModel(len(zonas),2)
modelo.setHorizontalHeaderLabels(['Zonas','Áreas'])

for linha, zona in enumerate(zonas):   
    elemento = QStandardItem(zona)
    modelo.setItem(linha, 0, elemento)

filtro = QSortFilterProxyModel()
filtro.setSourceModel(modelo)
filtro.setFilterKeyColumn(0)
filtro.setFilterCaseSensitivity(Qt.CaseInsensitive)

for linha, região in enumerate(nome_região):   
    elemento = QStandardItem(região)
    modelo.setItem(linha, 1, elemento)

filtro = QSortFilterProxyModel()
filtro.setSourceModel(modelo)
filtro.setFilterKeyColumn(1)
filtro.setFilterCaseSensitivity(Qt.CaseInsensitive)

app=QtWidgets.QApplication([])
tela=uic.loadUi("layout.ui")
tela.tableView.setModel(filtro)
tela.tableView.horizontalHeader().setStyleSheet("font-size: 35px;color: rgb(50, 50, 255);")
tela.barra_pesquisa.textChanged.connect(filtro.setFilterRegExp)

tela.show()
app.exec()